debug: true

cleanup: true

hostname: "{{ inventory_hostname }}"

clustername: "{{ xtoph_vars.clustername }}"

selected_profile:
  kickstart: "{{ h_ksPROF | default ('') }}"
  machine:   "{{ h_hwPROF | default ('') }}"
  platform:  "{{ h_plPROF | default ('') }}"
  resource:  "{{ h_rsPROF | default ('') }}"

deployhost:

  ##
  ##     platform_enable: one or more of the following
  ##       - "ovirt" 
  ##       - "libvirt"
  ##       - "baremetal"
  ##

  platform_enable: 
    - "libvirt"
    
  ##
  ##    deployhost hostname OR ip that will
  ##    accessible to the deployed VMs
  ##

  ip: "{{ xtoph_vars.deployhost_ip }}"

  ##
  ##    dnsmasq_enable:    ensures dnsmasq is installed
  ##                       and enabled on the deployhost
  ##
  ##    dnsmasq_asprimary  host/vm resolves to ->
  ##                         deployhost which forwards to ->
  ##                           real-dns
  ##

  dnsmasq_enable:     true
  dnsmasq_asprimary:  true

  ##
  ##    http_port:      port to provide kickstart and
  ##                    yum repo services
  ##

  http_enable:  true
  http_port:    "8008"

  ##
  ##    cockpit_enable: install and configure cockpit
  ##
  ##    cockpit_port:   defaults to 9090 if left empty
  ##                    if you change it, the config
  ##                    will ADD the specifed port.
  ##

  cockpit_enable:  true
  cockpit_port:    ""

  ##
  ##    temporary directory for various tasks
  ##
  ##    NOTE: needs to be unique for every host
  ##

  tmp_dir: "/home/tmp/{{ xtoph_vars.clustername }}/{{ inventory_hostname }}"

  ##
  ##    Where with the kickstart configs are stored 
  ##    What is the URL to access the kickstarts
  ##

  kickstart:
    dir: "/var/www/html/ks"
    url: "http://{{ xtoph_vars.deployhost_ip }}:8008/ks"

  ##
  ##    Where will the repos be mounted
  ##    What is the URL to access the repos
  ##

  repos:
    dir: "/var/www/html/repos"
    url: "http://{{ xtoph_vars.deployhost_ip }}:8008/repos"

  ##
  ##    Where are the ISOs stored
  ##

  iso:
    dir: "/home/iso"
