---
- hosts: node1
  tasks:
  
    - name: "SETUP TLOG: yum install packages"
      yum: name=tlog,cockpit-session-recording state=installed
      
    - name: "USER create and/or reset users"
      user: name="other-user"

    - name: "Sudo Configuration"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0600
      with_items:
        - {src: 'sudoers-student.j2', dest: '/etc/sudoers.d/oher-user

    - name: "SETUP TLOG: config file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0600
      with_items:
        - {src: 'tlog-config.j2', dest: '/etc/sssd/conf.d/sssd-session-recording.conf'} 

    - name: "SETUP TLOG: cheat file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-tlog-checkhost.sh'} 
        - {src: 'cheat-tlog-playback.j2', dest: '/usr/local/bin/cheat-tlog-playback.sh'} 

    - name: "SETUP TLOG: service restart"
      service: name="sssd" state=restarted enabled=yes
